TOKEN = "6037413508:AAGyScVhUxu8RGlIz40kRq7EyoQb3C0QCb8"


DATABASE_USER = "root"
DATABASE_PASSWORD = "qwerty123"
DATABASE_HOST = "localhost"
DATABASE_NAME = "car_db"

# Ссылка на базу данных
MYSQL_URL = f"mysql+pymysql://{DATABASE_USER}:{DATABASE_PASSWORD}@{DATABASE_HOST}/{DATABASE_NAME}"



